### ISSUE TITLE
App freeze and forces me to hard reset 3DS (probably related to gamecard)

### ISSUE THREAD

**Issue by Yoshistar95** [TuxSH/TWLSaveTool#10]
This is probably related to my bad gamecard of EoD, but when I press Y to restart or start the app up, it freezes. It only shows the app version line if I restarted, black screen when starting up.
I own two copies of EoD, other one worked just fine, so it probably is the card or the save, any way to get around it? I don't like to give up on trying to recover from this save error I keep getting when booting up the game :/

**Comment by TuxSH** [comment]
I don't have this problem with my EoT cartridge either.

When it hangs where described, it's always because of the cartridge (the save chip). Try removing the calls to https://github.com/TuxSH/TWLSaveTool/blob/master/source/SPI.cpp#L113 maybe but I don't think it will solve your issue.

**Comment by Yoshistar95** [comment]
Hmmm okay, I'll get to it once I can use a computer with internet at monday to use an online compiler, since this stupid make thing keeps nagging me it's not supported by the system. (and google didn't help me why it says that)

**Comment by drewbyhk** [comment]
I'm getting the same problem with WarioWare D.I.Y., but I've heard some wacky stuff about the saves with this game...

**Comment by TuxSH** [comment]
WarioWare D.I.Y is not supported by TWLSaveTool (the way the save is stored is out of TWLSaveTool's scope)
