### ISSUE TITLE
3dsx build crashes with error code on start when loaded from Luma3DS 8.1

### ISSUE THREAD

**Issue by Rust-and-Sunset** [TuxSH/TWLSaveTool#21]
Simple enough, really- whenever the program is loaded from new_hbmenu/Rosalina on Luma3DS 8.1, this error is displayed:

```
TWLSaveTool 1.1 by TuxSH

An error occurred:
   - Error code: e1213401
   - File: TWLCard.cpp, line 154

Press START to exit, Y to restart.
```

This occurs whether or not a DS cartridge is inserted into the system at the time.

Luma3DS 8.1 stable, EUR New 3DS XL, 11.4 firmware.

**Comment by TuxSH** [comment]
you need to enable "patch arm9 access" in the luma menu
