### ISSUE TITLE
Well Then Don't Use TWLSaveTool On....

### ISSUE THREAD

**Issue by gatekeeper1122** [TuxSH/TWLSaveTool#27]
i dont know how to start this off but lets get to the point then shall we?

2 days ago i decided to come back to the 3DS scene on the homebrew discord asking if its safe to update & if there were any homebrew apps that wouldn't work right? i was told to update luma to 9.1 & then just update so i did then short after i noticed i started crashing alot so i was like wtf i update to the latest (11.10.0-43U) & all there is crashing i now regret updating then i started to look at more & found out something was corrupt & that was the TWL save Tool so down below you can see the crash in the picture i dont know why or what happened but dont use v1.1 on (11.10.0-43U) or you will get stuck in a infinite crashing loop if you enter your settings & try to delete it or access it through FBI app if it wasn't for the update v1.2 my 3DS would have been a brick at this point cuz i couldnt think of any possible play to delete it with any type of homebrew app & none of the devs on anything for homebrew will ever reply to my messages overall now since the crashing is fixed finally i can now go back to what i was doing

heres the crash log
https://www.sendspace.com/file/vk8reo

![Mqxakxq](https://user-images.githubusercontent.com/16184353/58630636-4031e980-829d-11e9-9744-ad761faea256.jpg)

**Comment by Masamune3210** [comment]
If something ever happens like that, you can remove the SD card as only DS games are installed to the nand
