### ISSUE TITLE
the app crashes when opened

### ISSUE THREAD

**Issue by Pearl8520** [TuxSH/TWLSaveTool#31]
i'll attach a crash dump file to this report in .zip format since github doesnt support .dmp files
[crash_dump_00000002.zip](https://github.com/TuxSH/TWLSaveTool/files/7382803/crash_dump_00000002.zip)
rt

**Comment by ZephaniahNoah** [comment]
I'm having the same issue. Nothing I try works. It always crashes.
I'm running the latest firmware (11.17) on a New 2DS XL

**Comment by LopesLuna** [comment]
Same here- latest firmware, New 3DS XL

**Comment by TuxSH** [comment]
Give latest release a try.
