### ISSUE TITLE
[Request] Layout similar to that of the NDS version

### ISSUE THREAD

**Issue by ghost** [TuxSH/TWLSaveTool#4]
Do you think the UI could be designed to be more like this: https://gbatemp.net/screenshots/[2719]ndsbackuptool.jpg  ?

As for key mapping, do you think they could be re-arranged to be more like this:

B - Backup (Hence the letter B xD)
A - Select a save file to restore/restore save file
X - Delete save from the card
Y - Refresh/Restart
Start - Exit

Is it also possible to dump the NDS card ROM itself or is that not possible?

**Comment by ghost** [comment]
Also my L key is broken and can't build the source code ATM XD

**Comment by ihaveamac** [comment]
I can say, at least for ROM dumping, that there "might" be unused code in uncart for that. https://gbatemp.net/posts/6033749/

**Comment by ghost** [comment]
OOh. I think I remember looking at that some time ago but never did anything with it.

Trying to get makerom and bannertool for Linux, atm 0~0
