### ISSUE TITLE
Feature suggestion: Dump DSiWare saves

### ISSUE THREAD

**Issue by thejsa** [TuxSH/TWLSaveTool#9]
Is it possible to dump DSiWare saves? It would be really handy because it would then allow me to savehack Flipnote Studio (CIA repack of the DSiWare) to put my old DSi's Flipnote Studio ID in, allowing me to use Sudomemo.

**Comment by TuxSH** [comment]
TWLNandFiler is the official tool for this (it's included in the CTR SDK), and does its job quite well.
It's been repacked for retail consoles recently (you'll need to grab the recent TWL_FIRM patches to launch it).
